/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "surface-container-lowest": "#001a13",
        "surface-container-low": "#0f3b2e",
        "text-main": "#fbf9f3",
        "on-secondary-fixed": "#002116",
        "tertiary-fixed-dim": "#e4c373",
        "surface-dim": "#001a13",
        "secondary-fixed": "#b2f0d5",
        "outline-variant": "#414845",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#a4d0be",
        "on-tertiary-container": "#503d00",
        "surface-bright": "#0f3b2e",
        "on-primary-fixed-variant": "#254e40",
        "on-tertiary-fixed": "#251a00",
        "surface-muted": "#0a2e24",
        "on-primary-container": "#7aa694",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#594400",
        "surface-variant": "#0f3b2e",
        "outline": "#717974",
        "secondary": "#2e6954",
        "on-secondary-fixed-variant": "#10503d",
        "olive-accent": "#7A8E46",
        "tertiary": "#c7a85b",
        "on-surface": "#fbf9f3",
        "primary-container": "#0f3b2e",
        "text-muted": "#a4d0be",
        "primary": "#bfecd9",
        "on-tertiary": "#00241a",
        "on-secondary-container": "#346f5a",
        "error": "#ba1a1a",
        "background": "#00241a",
        "on-surface-variant": "#c0c8c3",
        "surface-container": "#0f3b2e",
        "surface-card": "#0f3b2e",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#97d3b9",
        "surface-tint": "#3d6657",
        "tertiary-fixed": "#ffdf95",
        "tertiary-container": "#c7a85b",
        "secondary-container": "#2e6954",
        "primary-fixed": "#bfecd9",
        "on-primary-fixed": "#002117",
        "on-background": "#fbf9f3",
        "inverse-surface": "#fbf9f3",
        "surface-container-high": "#1a473a",
        "inverse-on-surface": "#00241a",
        "surface": "#00241a",
        "inverse-primary": "#006b54",
        "surface-container-highest": "#1f5042",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "section-gap-md": "80px",
        "section-gap-lg": "120px",
        "margin-mobile": "16px",
        "base": "8px",
        "gutter": "24px"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "quote-editorial": ["Source Serif 4", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Source Serif 4", "serif"],
        "display-lg": ["Source Serif 4", "serif"],
        "display-lg-mobile": ["Source Serif 4", "serif"],
        "headline-md": ["Source Serif 4", "serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "quote-editorial": ["22px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "display-lg": ["56px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "display-lg-mobile": ["40px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
